### ISSUE TITLE
Add active class to table td

### ISSUE THREAD

**Issue by duffyjp** [DFMCH/dfm_web#23]
``` css
td.active::before {
  content: "☑";
  color: green;
  font-size: 1.6em;
}
```

Something like this:  http://localhost:3000/compensation/periods

<img width="190" alt="screen shot 2016-07-14 at 10 31 47 am" src="https://cloud.githubusercontent.com/assets/382216/16845356/3937e970-49ae-11e6-97e7-3658f29ce53a.png">

Can be used to replace the png used in PIMS.

<img width="420" alt="screen shot 2016-07-14 at 10 33 24 am" src="https://cloud.githubusercontent.com/assets/382216/16845420/79a950d4-49ae-11e6-9094-f85f20154cfa.png">
